import localFont from "next/font/local";
import "./globals.css";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Separator } from "@/components/ui/separator";

import { ThemeProvider } from "@/components/theme-provider";

import { ReactFlowProvider } from "@xyflow/react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="w-screen">
            <SidebarInset>
              <header className="">
                <nav className="flex items-center jus h-12">
                  <SidebarTrigger className="ml-2 " />
                </nav>
                <Separator />
              </header>
              <ThemeProvider
                attribute="class"
                defaultTheme="dark"
                enableSystem
                disableTransitionOnChange
              >
                <ReactFlowProvider>{children}</ReactFlowProvider>
              </ThemeProvider>
            </SidebarInset>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
